<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <!-- Habilitar auto geração de doc -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!--<NoWarn>$(NoWarn);1591</NoWarn>-->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    </ItemGroup>
</Project>
