// <auto-generated />
using System;
using Claims.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Claims.Api.Data.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20260921155432_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Claims.Api.Domain.Beneficiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carteirinha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("FimCarencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("InicioVigencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFicticio")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Carteirinha")
                        .IsUnique();

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("Claims.Api.Domain.GuiaConsulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BeneficiarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataAtendimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrestadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiarioId");

                    b.HasIndex("LoteId");

                    b.HasIndex("PrestadorId");

                    b.ToTable("GuiasConsulta");
                });

            modelBuilder.Entity("Claims.Api.Domain.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("Claims.Api.Domain.Prestador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CredenciadoAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeFicticio")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prestadores");
                });

            modelBuilder.Entity("Claims.Api.Domain.GuiaConsulta", b =>
                {
                    b.HasOne("Claims.Api.Domain.Beneficiario", null)
                        .WithMany()
                        .HasForeignKey("BeneficiarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Claims.Api.Domain.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Claims.Api.Domain.Prestador", null)
                        .WithMany()
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
